#!/usr/bin/env bash
# Submit CS416 project programs as a job to ada

# Set SLURM options (you should not need to change these)
#SBATCH --job-name=pa1                          # Job name
#SBATCH --output=Project-%j.out           # Name for output log file (%j is job ID)
#SBATCH --cpus-per-task=36                      # Request the entire node
#SBATCH --partition=short                       # Partition (queue) 
#SBATCH --time=00:10:00                         # Time limit hrs:min:sec
#SBATCH --exclude=node[018-019,021-022]         # Only use "original" nodes with 36 cores

# DON'T MODIFY THE SLURM OPTIONS ABOVE THIS LINE

# Job start info
echo "# Job Info ----------------------------"
echo "Job ID: ${SLURM_JOB_ID}"
echo "Node: ${SLURMD_NODENAME}"
echo "Starting: $(date +"%D %T")"

GRAPH_FILE="tests/synthetic_graph10mil.txt"

echo -e "\n# Graph Size --------------------------"
wc -l "$GRAPH_FILE"

# Run Serial Implementation
echo -e "\n# Serial Results -------------------------\n"

echo -e "\nRunning synthetic_graph.txt"
./pagerankSerial "$GRAPH_FILE"

# Run OpenMP Parallel Implementation 
echo -e "\n# Parallel Results -------------------------\n"

echo -e "\nRunning synthetic_graph.txt"

for NUM_THREADS in 8 16; do
  echo -e "\n# OpenMP Results with $NUM_THREADS threads -------------------------\n"
  echo "Running with $NUM_THREADS threads (cores 0-$((NUM_THREADS - 1)))"
  taskset -c 0-$((NUM_THREADS - 1)) ./pagerank "$GRAPH_FILE"
done

# Dump system info for reproducibility
echo -e "\n# CPU Info ----------------------------"
lscpu


#