#!/usr/bin/env bash
# Submit CS416 project programs as a job to ada

# Set SLURM options (you should not need to change these)
#SBATCH --job-name=pa1                          # Job name
#SBATCH --output=Project-%j.out           # Name for output log file (%j is job ID)
#SBATCH --cpus-per-task=36                      # Request the entire node
#SBATCH --partition=short                       # Partition (queue) 
#SBATCH --time=00:05:00                         # Time limit hrs:min:sec
#SBATCH --exclude=node[018-019,021-022]         # Only use "original" nodes with 36 cores

# DON'T MODIFY THE SLURM OPTIONS ABOVE THIS LINE

# Job start info
echo "# Job Info ----------------------------"
echo "Job ID: ${SLURM_JOB_ID}"
echo "Node: ${SLURMD_NODENAME}"
echo "Starting: $(date +"%D %T")"

echo -e "\n# Run Results -------------------------\n"

# Run Serial Implementation
echo -e "\n# Serial Results -------------------------\n"
echo "Running small_graph.txt"
./pagerankSerial tests/small_graph.txt

echo -e "\nRunning benchmark_graph.txt"
./pagerankSerial tests/benchmark_graph.txt

# Run OpenMP Parallel Implementation with core binding to cores 0-7
echo -e "\n# Parallel Results (taskset 0–7) -------------------------\n"
echo "Running small_graph.txt with taskset"
taskset -c 0-7 ./pagerank tests/small_graph.txt

echo -e "\nRunning benchmark_graph.txt with taskset"
taskset -c 0-7 ./pagerank tests/benchmark_graph.txt

# Dump system info for reproducibility
echo -e "\n# CPU Info ----------------------------"
lscpu
